name: Deploy Mantools to VPS

# on.push.branches.main -> pipeline runs automatically every time a push is made to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        # actions/checkout -> take source code from repo
      - name: Checkout source code
        uses: actions/checkout@v4

        # SSh Setup:
        # 1. create SSH folder in GitHub runner
        # 2. inject private key from GitHub Secrets
        # 3. permission is MANDATORY for SSH to be accepted
        # 4. prevent host authenticity errors
      - name: SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        # Deploy via SSH:
        # 1. ssh user@host << EOF -> run multiple commands on VPS
        # 2. git pull -> update source code
        # 3. docker compose build -> rebuild image
        # 4. docker compose up -d -> restart container without down server
      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            docker compose build
            docker compose up -d
          EOF